// Code generated by protoc-gen-go. DO NOT EDIT.
// source: employee.proto

package hrd

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Salary struct {
	Amount               float64  `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string   `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Salary) Reset()         { *m = Salary{} }
func (m *Salary) String() string { return proto.CompactTextString(m) }
func (*Salary) ProtoMessage()    {}
func (*Salary) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{0}
}

func (m *Salary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Salary.Unmarshal(m, b)
}
func (m *Salary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Salary.Marshal(b, m, deterministic)
}
func (m *Salary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Salary.Merge(m, src)
}
func (m *Salary) XXX_Size() int {
	return xxx_messageInfo_Salary.Size(m)
}
func (m *Salary) XXX_DiscardUnknown() {
	xxx_messageInfo_Salary.DiscardUnknown(m)
}

var xxx_messageInfo_Salary proto.InternalMessageInfo

func (m *Salary) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Salary) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type Employee struct {
	Firstname            string   `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	EducationLevel       int32    `protobuf:"varint,3,opt,name=education_level,json=educationLevel,proto3" json:"education_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Employee) Reset()         { *m = Employee{} }
func (m *Employee) String() string { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()    {}
func (*Employee) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{1}
}

func (m *Employee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Employee.Unmarshal(m, b)
}
func (m *Employee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Employee.Marshal(b, m, deterministic)
}
func (m *Employee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Employee.Merge(m, src)
}
func (m *Employee) XXX_Size() int {
	return xxx_messageInfo_Employee.Size(m)
}
func (m *Employee) XXX_DiscardUnknown() {
	xxx_messageInfo_Employee.DiscardUnknown(m)
}

var xxx_messageInfo_Employee proto.InternalMessageInfo

func (m *Employee) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Employee) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Employee) GetEducationLevel() int32 {
	if m != nil {
		return m.EducationLevel
	}
	return 0
}

type EmployeeResponse struct {
	Id                   int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Employee             *Employee   `protobuf:"bytes,2,opt,name=employee,proto3" json:"employee,omitempty"`
	Department           *Department `protobuf:"bytes,3,opt,name=department,proto3" json:"department,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *EmployeeResponse) Reset()         { *m = EmployeeResponse{} }
func (m *EmployeeResponse) String() string { return proto.CompactTextString(m) }
func (*EmployeeResponse) ProtoMessage()    {}
func (*EmployeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{2}
}

func (m *EmployeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeResponse.Unmarshal(m, b)
}
func (m *EmployeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeResponse.Marshal(b, m, deterministic)
}
func (m *EmployeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeResponse.Merge(m, src)
}
func (m *EmployeeResponse) XXX_Size() int {
	return xxx_messageInfo_EmployeeResponse.Size(m)
}
func (m *EmployeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeResponse proto.InternalMessageInfo

func (m *EmployeeResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EmployeeResponse) GetEmployee() *Employee {
	if m != nil {
		return m.Employee
	}
	return nil
}

func (m *EmployeeResponse) GetDepartment() *Department {
	if m != nil {
		return m.Department
	}
	return nil
}

type Department struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Department) Reset()         { *m = Department{} }
func (m *Department) String() string { return proto.CompactTextString(m) }
func (*Department) ProtoMessage()    {}
func (*Department) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{3}
}

func (m *Department) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Department.Unmarshal(m, b)
}
func (m *Department) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Department.Marshal(b, m, deterministic)
}
func (m *Department) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Department.Merge(m, src)
}
func (m *Department) XXX_Size() int {
	return xxx_messageInfo_Department.Size(m)
}
func (m *Department) XXX_DiscardUnknown() {
	xxx_messageInfo_Department.DiscardUnknown(m)
}

var xxx_messageInfo_Department proto.InternalMessageInfo

func (m *Department) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Salary)(nil), "hrd.Salary")
	proto.RegisterType((*Employee)(nil), "hrd.Employee")
	proto.RegisterType((*EmployeeResponse)(nil), "hrd.EmployeeResponse")
	proto.RegisterType((*Department)(nil), "hrd.Department")
}

func init() { proto.RegisterFile("employee.proto", fileDescriptor_eb50a19aa79a6eac) }

var fileDescriptor_eb50a19aa79a6eac = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0xbf, 0x4f, 0xf3, 0x30,
	0x10, 0x6d, 0xda, 0xaf, 0x55, 0x73, 0x55, 0xd3, 0x4f, 0x27, 0x81, 0xaa, 0x8a, 0x21, 0xf2, 0x42,
	0xbb, 0x14, 0xa9, 0x2c, 0x0c, 0x4c, 0xfc, 0x10, 0x0c, 0x4c, 0x66, 0x63, 0x41, 0x26, 0x3e, 0xd4,
	0x48, 0xb1, 0x1d, 0x39, 0x0e, 0x52, 0x17, 0xfe, 0x76, 0x54, 0xe3, 0xb8, 0x2d, 0x9b, 0xdf, 0x7b,
	0x77, 0xef, 0xdd, 0xf9, 0x20, 0x23, 0x55, 0x57, 0x66, 0x47, 0xb4, 0xae, 0xad, 0x71, 0x06, 0x07,
	0x5b, 0x2b, 0xd9, 0x2d, 0x8c, 0x5e, 0x45, 0x25, 0xec, 0x0e, 0xcf, 0x61, 0x24, 0x94, 0x69, 0xb5,
	0x9b, 0x27, 0x79, 0xb2, 0x4c, 0x78, 0x40, 0xb8, 0x80, 0x71, 0xd1, 0x5a, 0x4b, 0xba, 0xd8, 0xcd,
	0xfb, 0x79, 0xb2, 0x4c, 0x79, 0xc4, 0x4c, 0xc1, 0xf8, 0x31, 0x98, 0xe2, 0x05, 0xa4, 0x9f, 0xa5,
	0x6d, 0x9c, 0x16, 0x8a, 0xbc, 0x45, 0xca, 0x0f, 0xc4, 0xde, 0xa5, 0x12, 0x41, 0x0c, 0x2e, 0x1d,
	0xc6, 0x4b, 0x98, 0x91, 0x6c, 0x0b, 0xe1, 0x4a, 0xa3, 0xdf, 0x2b, 0xfa, 0xa2, 0x6a, 0x3e, 0xc8,
	0x93, 0xe5, 0x90, 0x67, 0x91, 0x7e, 0xd9, 0xb3, 0xec, 0x1b, 0xfe, 0x77, 0x71, 0x9c, 0x9a, 0xda,
	0xe8, 0x86, 0x30, 0x83, 0x7e, 0x29, 0x7d, 0xde, 0x80, 0xf7, 0x4b, 0x89, 0x2b, 0x18, 0x77, 0x7b,
	0xfa, 0xa0, 0xc9, 0x66, 0xba, 0xde, 0x5a, 0xb9, 0x8e, 0x8d, 0x51, 0xc6, 0x2b, 0x00, 0x49, 0xb5,
	0xb0, 0x4e, 0x91, 0x76, 0x3e, 0x72, 0xb2, 0x99, 0xf9, 0xe2, 0x87, 0x48, 0xf3, 0xa3, 0x12, 0x96,
	0x03, 0x1c, 0x14, 0x44, 0xf8, 0x77, 0xb4, 0xab, 0x7f, 0x6f, 0x1c, 0x4c, 0x9f, 0x5b, 0x25, 0x34,
	0xa7, 0xc6, 0xb4, 0xb6, 0x20, 0xbc, 0x81, 0xec, 0xde, 0x92, 0x70, 0x14, 0xff, 0xe9, 0x74, 0x9c,
	0xc5, 0xd9, 0xe9, 0x74, 0x61, 0x2d, 0xd6, 0xc3, 0x15, 0xa4, 0x4f, 0xe4, 0xc2, 0x71, 0xfe, 0x34,
	0x4d, 0x3c, 0xfc, 0xd5, 0x58, 0xef, 0x6e, 0xf8, 0xb6, 0xbf, 0xe5, 0xc7, 0xc8, 0xdf, 0xf5, 0xfa,
	0x27, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x87, 0xd4, 0x82, 0xe9, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HumanResourceClient is the client API for HumanResource service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HumanResourceClient interface {
	CreateEmployee(ctx context.Context, in *Employee, opts ...grpc.CallOption) (*EmployeeResponse, error)
	GetSalary(ctx context.Context, in *Employee, opts ...grpc.CallOption) (*Salary, error)
}

type humanResourceClient struct {
	cc *grpc.ClientConn
}

func NewHumanResourceClient(cc *grpc.ClientConn) HumanResourceClient {
	return &humanResourceClient{cc}
}

func (c *humanResourceClient) CreateEmployee(ctx context.Context, in *Employee, opts ...grpc.CallOption) (*EmployeeResponse, error) {
	out := new(EmployeeResponse)
	err := c.cc.Invoke(ctx, "/hrd.HumanResource/CreateEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *humanResourceClient) GetSalary(ctx context.Context, in *Employee, opts ...grpc.CallOption) (*Salary, error) {
	out := new(Salary)
	err := c.cc.Invoke(ctx, "/hrd.HumanResource/GetSalary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HumanResourceServer is the server API for HumanResource service.
type HumanResourceServer interface {
	CreateEmployee(context.Context, *Employee) (*EmployeeResponse, error)
	GetSalary(context.Context, *Employee) (*Salary, error)
}

// UnimplementedHumanResourceServer can be embedded to have forward compatible implementations.
type UnimplementedHumanResourceServer struct {
}

func (*UnimplementedHumanResourceServer) CreateEmployee(ctx context.Context, req *Employee) (*EmployeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEmployee not implemented")
}
func (*UnimplementedHumanResourceServer) GetSalary(ctx context.Context, req *Employee) (*Salary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSalary not implemented")
}

func RegisterHumanResourceServer(s *grpc.Server, srv HumanResourceServer) {
	s.RegisterService(&_HumanResource_serviceDesc, srv)
}

func _HumanResource_CreateEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Employee)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HumanResourceServer).CreateEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hrd.HumanResource/CreateEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HumanResourceServer).CreateEmployee(ctx, req.(*Employee))
	}
	return interceptor(ctx, in, info, handler)
}

func _HumanResource_GetSalary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Employee)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HumanResourceServer).GetSalary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hrd.HumanResource/GetSalary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HumanResourceServer).GetSalary(ctx, req.(*Employee))
	}
	return interceptor(ctx, in, info, handler)
}

var _HumanResource_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hrd.HumanResource",
	HandlerType: (*HumanResourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEmployee",
			Handler:    _HumanResource_CreateEmployee_Handler,
		},
		{
			MethodName: "GetSalary",
			Handler:    _HumanResource_GetSalary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "employee.proto",
}
